[tox]
envlist = py3{10,11,12,13,14},lint,type,duplication
requires = tox-uv

[testenv]
extras = test
commands = pytest {posargs:-n 6 --dist loadscope tests/}

[testenv:lint]
extras = devel
commands = ruff check src/ tests/

[testenv:type]
extras = devel
commands = mypy --ignore-missing-imports src/bids_utils/

[testenv:duplication]
extras = devel
commands = pylint --disable=all --enable=duplicate-code src/bids_utils/

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312, lint, type, duplication
    3.13: py313
    3.14: py314
